namespace Dollibar.Cllient.Dtos.ProposalsDto
{
    public class ProposalDto
    {
        public string? Module { get; set; }
        public int Id { get; set; }
        public string? Entity { get; set; }
        public List<string>? Contacts_ids { get; set; }
        public string? Fk_project { get; set; }
        public string? Contact_id { get; set; }
        public string? Ref { get; set; }
        public string? Ref_ext { get; set; }
        public int? Statut { get; set; }
        public int? Status { get; set; }
        public string? Country_id { get; set; }
        public string? Country_code { get; set; }
        public string? State_id { get; set; }
        public string? Region_id { get; set; }
        public string? Mode_reglement_id { get; set; }
        public string? Cond_reglement_id { get; set; }
        public string? Demand_reason_id { get; set; }
        public string? Transport_mode_id { get; set; }
        public string? Shipping_method_id { get; set; }
        public string? Shipping_method { get; set; }
        public string? Multicurrency_code { get; set; }
        public string? Multicurrency_tx { get; set; }
        public string? Model_pdf { get; set; }
        public string? Last_main_doc { get; set; }
        public string? Note_public { get; set; }
        public string? Note_private { get; set; }
        public string? Total_ht { get; set; }
        public string? Total_tva { get; set; }
        public string? Total_localtax1 { get; set; }
        public string? Ttal_localtax2 { get; set; }
        public string? Total_ttc { get; set; }
        public int? Date_creation { get; set; }
        public int? Date_modification { get; set; }
        public int? Date_update { get; set; }
        public int? Date_cloture { get; set; }
        public int? User_creation_id { get; set; }
        public int? User_validation_id { get; set; }
        public int? User_closing_id { get; set; }
        public int? User_modification { get; set; }
        public int? User_modification_id { get; set; }
        public int? Specimen { get; set; }
        public string? Code { get; set; }
        public string? Socid { get; set; }
        public object? Contactid { get; set; }
        public string? Ref_client { get; set; }
        public int? Datec { get; set; }
        public string? Datev { get; set; }
        public string? Date_signature { get; set; }
        public string? User_signature { get; set; }
        public int? Date { get; set; }
        public int? Datep { get; set; }
        public int? Date_livraison { get; set; }
        public int? Delivery_date { get; set; }
        public int? Fin_validite { get; set; }
        public string? User_author_id { get; set; }
        public string? User_valid_id { get; set; }
        public string? User_close_id { get; set; }
        public string? Price { get; set; }
        public string? Total { get; set; }
        public string? Cond_reglement_code { get; set; }
        public string? Cond_reglement_doc { get; set; }
        public string? Mode_reglement_code { get; set; }
        public string? Remise_percent { get; set; }
        public string? Remise { get; set; }
        public string? remise_absolue { get; set; }
        public string? Fk_address { get; set; }
        public string? Availability_id { get; set; }
        public string? Availability_code { get; set; }
        public int? Duree_validite { get; set; }
        public string? Demand_reason_code { get; set; }
        public string? Fk_multicurrency { get; set; }
        public string? Multicurrency_total_ht { get; set; }
        public string? Multicurrency_total_tva { get; set; }
        public string? Multicurrency_total_ttc { get; set; }
        public string? Fk_incoterms { get; set; }
        public string? Location_incoterms { get; set; }
        public string? Ref_customer { get; set; }
        public string? Availability { get; set; }
        public string? Demand_reason { get; set; }
        public int? Brouillon { get; set; }
    }
}
